In [7]:
#Program 1: Calculate total weekly energy from a list
DAILY_KWH = [400, 850, 400, 350, 500, 600]
total_energy = sum(DAILY_KWH)
print("Total energy used:", total_energy, "KWH")

Total energy used: 3100 KWH

In [8]:
#Program 2: Store building usage data
building_usage = {
    "CSE": 400,
    "Hostel": 850
}
print("Hostel used:", building_usage["Hostel"], "KWH")

Hostel used: 850 KWH

In [3]:
#Program 3: A function to calculate electricity cost
def calculate_bill(kWH, rate_per_unit):
    return kWH * rate_per_unit
todays_bill = calculate_bill(850, 8)
print("Today's estimated bill is Rs.", todays_bill)

Today's estimated bill is Rs. 6800

In [4]:
#Program 4: Read a file line by line
with open("campus_energy.csv", "r") as file:
  for line in file.readlines():
    print(line.strip())

DATE,BUILDING,KWH_USED,PEAK_HOUR_USAGE
5/10/2026,CSE,400,350
6/10/2026,HOSTEL,850,240
7/10/2026,CSE,400,555
8/10/2026,ECE,350,645
9/10/2026,CIVIL,500,210
10/10/2026,HOSTEL,600,111

In [6]:
# Import the pandas libary
import pandas as pd

#Load the dataset you created
df = pd.read_csv('campus_energy.csv')

#Display the first few rows of the data
print("Here is the raw data:")
display(df.head())

#Group the data to see total usage per building
BUILDING_totals = df.groupby('BUILDING')['KWH_USED'].sum()
print("\nTotal USAGE PER BUILDING:")
print(BUILDING_totals)

#Generate a statistical summary (average, min, max) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

        DATE BUILDING  KWH_USED  PEAK_HOUR_USAGE
0  5/10/2026      CSE       400              350
1  6/10/2026   HOSTEL       850              240
2  7/10/2026      CSE       400              555
3  8/10/2026      ECE       350              645
4  9/10/2026    CIVIL       500              210

Total USAGE PER BUILDING:
BUILDING
CIVIL      500
CSE        800
ECE        350
HOSTEL    1450
Name: KWH_USED, dtype: int64

Statistical Summary:

         KWH_USED  PEAK_HOUR_USAGE
count    6.000000         6.000000
mean   516.666667       351.833333
std    186.189867       208.734680
min    350.000000       111.000000
25%    400.000000       217.500000
50%    450.000000       295.000000
75%    575.000000       503.750000
max    850.000000       645.000000

In [9]:
# Create the README .md file and write a message inside it
with open("README.md", "w") as file:
  file.write("# Smart Campus Energy Project\n")
  file.write("This repository contains my Week 1 hands-on Python and pandas assignments.\n")
  file.write("Created by: [Ramya thuthika]")
print("README.md has been successsfully created!")

README.md has been successsfully created!